### ISSUE TITLE
Change states

### ISSUE THREAD

**Issue by alorma** [fstech/android-floating-action-button#5]
Change FAB state when click.

Allow icon to animate, like AddFAB to change into loading, etc.

Enable 'enabled' state

**Comment by AndroidDeveloperLB** [comment]
Is it possible to animate the main FAB (the one that opens the menu) ? 
It could be useful for when I navigate between fragments on a ViewPager, when a different FAB is needed to be shown for each of them.

**Comment by AndroidDeveloperLB** [comment]
Closed because?

**Comment by alorma** [comment]
Because of 5 years ago

**Comment by AndroidDeveloperLB** [comment]
Oh. I suggest to write something on the main page, if you mean that it's no longer maintained.
I think there is also a way to archive projects, blocking further comments and posts from being created. Not sure how.
I saw such cases. Maybe would help you deal with it.
:)

**Comment by alorma** [comment]
Repos can be archived...

But this is not my repo, so no much I can do...

**Comment by AndroidDeveloperLB** [comment]
Not yours? So how did you close the issue? It's possible to have multiple people having different "permissions" on the same repo?
